### ISSUE TITLE
New installs not working in demo mode

### ISSUE THREAD

**Issue by freshehr** [RippleOSI/Ripple-Qewd#89]
```
home/ian/qewd/node_modules/qewd-ripple/lib/startup.js:52
  if (qewd_jumper) {
      ^

ReferenceError: qewd_jumper is not defined
    at Object.start (/home/ian/qewd/node_modules/qewd-ripple/lib/startup.js:52:7)
    at Object.<anonymous> (/home/ian/qewd/ripple-demo.js:59:11)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

```

I succesfully installed the stack 2 weeks ago (Redis) but when I tied again today go the message above when starting node ripple-demo.js

Ian

**Comment by robtweed** [comment]
Sorry Ian - I'd not updated the repo properly.  Try the very latest build (2.33) from NPM
